/**
 * Single source of truth for product ("piece") OG bridge URLs.
 *
 * Bridge files are generated by the OG pipeline under public/share/og/ and are
 * indexed in public/og-manifest.json. Historically the client-side share button
 * guessed a filename ({designer}-{title}-og.html) while the pipeline sometimes
 * writes {brand}-{title}-{designer}-og.html — which produced 404 share links.
 *
 * This resolver never guesses: it matches against the real manifest and falls
 * back to the canonical product page URL (which always exists) when no bridge
 * is found, so a shared link can never 404.
 *
 * Self-contained on purpose (no imports from whatsapp-share) to avoid a cycle.
 */

const slugifyLocal = (s: string) =>
  s
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[éèêë]/g, "e")
    .replace(/[àâäáã]/g, "a")
    .replace(/[ùûüú]/g, "u")
    .replace(/[ôöóõ]/g, "o")
    .replace(/[îïí]/g, "i")
    .replace(/ç/g, "c")
    .replace(/ñ/g, "n")
    .replace(/ø/g, "o")
    .replace(/å/g, "a")
    .replace(/ř/g, "r")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

let cache: string[] | null = null;
let inflight: Promise<string[]> | null = null;

/** Synchronous access to the loaded manifest (null until preload resolves). */
export const getOgBridgeIndexSync = (): string[] | null => cache;

/** Load + cache the OG bridge manifest. Call once at app start. */
export const loadOgBridgeIndex = async (): Promise<string[]> => {
  if (cache) return cache;
  if (inflight) return inflight;
  inflight = fetch("/og-manifest.json", { cache: "force-cache" })
    .then((r) => (r.ok ? r.json() : []))
    .then((list: unknown) => {
      const paths = Array.isArray(list)
        ? (list as string[]).filter((p) => typeof p === "string" && p.startsWith("share/og/"))
        : [];
      cache = paths;
      return paths;
    })
    .catch(() => {
      cache = [];
      return cache;
    })
    .finally(() => {
      inflight = null;
    });
  return inflight;
};

/** Find the real bridge file for a piece, or null when none exists. */
export const findPieceBridgePath = (
  index: string[],
  designerName: string,
  pieceTitle: string,
  pieceSubtitle?: string | null,
): string | null => {
  const designer = slugifyLocal(designerName || "");
  const title = slugifyLocal(pieceTitle || "");
  const subtitle = pieceSubtitle ? slugifyLocal(pieceSubtitle) : "";
  if (!title) return null;

  const exact = [
    subtitle ? `share/og/${designer}-${title}-${subtitle}-og.html` : null,
    `share/og/${designer}-${title}-og.html`,
    subtitle ? `share/og/${subtitle}-${title}-og.html` : null,
  ].filter(Boolean) as string[];

  for (const candidate of exact) {
    if (index.includes(candidate)) return candidate;
  }

  // Fuzzy: the pipeline keys brand-first and may append the designer as suffix.
  const containsTitle = index.filter(
    (p) => p.includes(`-${title}-og.html`) || p.includes(`-${title}-`),
  );
  if (containsTitle.length) {
    const withBoth = containsTitle.filter(
      (p) => designer && subtitle && p.includes(designer) && p.includes(subtitle),
    );
    const withDesigner = containsTitle.filter((p) => designer && p.includes(designer));
    const withSubtitle = containsTitle.filter((p) => subtitle && p.includes(subtitle));
    const pick =
      withBoth[0] ??
      withDesigner[0] ??
      withSubtitle[0] ??
      (containsTitle.length === 1 ? containsTitle[0] : null);
    if (pick) return pick;
  }
  return null;
};
