/**
 * Single source of truth for product ("piece") OG bridge URLs.
 *
 * Bridge files are generated by the OG pipeline under public/share/og/ and are
 * indexed in public/og-manifest.json. Historically the client-side share button
 * guessed a filename ({designer}-{title}-og.html) while the pipeline sometimes
 * writes {brand}-{title}-{designer}-og.html — which produced 404 share links.
 *
 * This resolver never guesses: it matches against the real manifest and falls
 * back to the canonical product page URL (which always exists) when no bridge
 * is found, so a shared link can never 404.
 */
import { useEffect, useState } from "react";
import { slugify, withOgCacheBust } from "@/lib/whatsapp-share";

const SITE_URL = "https://maisonaffluency.com";

let cache: string[] | null = null;
let inflight: Promise<string[]> | null = null;

export const loadOgBridgeIndex = async (): Promise<string[]> => {
  if (cache) return cache;
  if (inflight) return inflight;
  inflight = fetch("/og-manifest.json", { cache: "force-cache" })
    .then((r) => (r.ok ? r.json() : []))
    .then((list: unknown) => {
      const paths = Array.isArray(list)
        ? (list as string[]).filter((p) => typeof p === "string" && p.startsWith("share/og/"))
        : [];
      cache = paths;
      return paths;
    })
    .catch(() => {
      cache = [];
      return [];
    })
    .finally(() => {
      inflight = null;
    });
  return inflight;
};

/** Find the real bridge file for a piece, or null when none exists. */
export const findPieceBridgePath = (
  index: string[],
  designerName: string,
  pieceTitle: string,
  pieceSubtitle?: string | null,
): string | null => {
  const designer = slugify(designerName);
  const title = slugify(pieceTitle);
  const subtitle = pieceSubtitle ? slugify(pieceSubtitle) : "";
  if (!title) return null;

  const exact = [
    subtitle ? `share/og/${designer}-${title}-${subtitle}-og.html` : null,
    `share/og/${designer}-${title}-og.html`,
    subtitle ? `share/og/${subtitle}-${title}-og.html` : null,
  ].filter(Boolean) as string[];

  for (const candidate of exact) {
    if (index.includes(candidate)) return candidate;
  }

  // Fuzzy: the pipeline keys brand-first and may append the designer as suffix.
  const containsTitle = index.filter((p) => p.includes(`-${title}-og.html`) || p.includes(`-${title}-`));
  if (containsTitle.length) {
    const withDesigner = containsTitle.filter((p) => designer && p.includes(designer));
    const withSubtitle = containsTitle.filter((p) => subtitle && p.includes(subtitle));
    const pick = withDesigner[0] ?? withSubtitle[0] ?? (containsTitle.length === 1 ? containsTitle[0] : null);
    if (pick) return pick;
  }
  return null;
};

/**
 * Resolve the share URL for a piece. Returns the canonical page URL until the
 * manifest resolves (and permanently if no bridge exists) — never a 404 guess.
 */
export const usePieceOgUrl = (
  designerName: string | null | undefined,
  pieceTitle: string | null | undefined,
  pieceSubtitle?: string | null,
  canonicalPath?: string,
): string => {
  const fallbackPath =
    canonicalPath ??
    (typeof window !== "undefined" && window.location.pathname !== "/"
      ? window.location.pathname
      : `/designers/${slugify(designerName ?? "")}`);
  const fallback = `${SITE_URL}${fallbackPath}`;
  const [url, setUrl] = useState(fallback);

  useEffect(() => {
    let cancelled = false;
    if (!designerName || !pieceTitle) {
      setUrl(fallback);
      return;
    }
    loadOgBridgeIndex().then((index) => {
      if (cancelled) return;
      const path = findPieceBridgePath(index, designerName, pieceTitle, pieceSubtitle);
      setUrl(path ? withOgCacheBust(`${SITE_URL}/${path}`) : fallback);
    });
    return () => {
      cancelled = true;
    };
  }, [designerName, pieceTitle, pieceSubtitle, fallback]);

  return url;
};
