import { chromium } from '@playwright/test';
const b = await chromium.launch();
const c = await b.newContext({ viewport:{width:390,height:844}, isMobile:true, hasTouch:true });
const pg = await c.newPage();
const errs=[]; pg.on('pageerror',e=>errs.push(String(e)));
await pg.goto('http://localhost:4321/', { waitUntil:'load' });
await pg.waitForTimeout(4000);
await pg.screenshot({path:'/tmp/browser/lt/home.png'});
console.log('banner', await pg.locator('[data-featured-read-banner]').count());
console.log('nav', await pg.locator('nav').count());
await pg.mouse.wheel(0, 4000); await pg.waitForTimeout(3000);
console.log('footer', await pg.locator('footer').count());
await pg.screenshot({path:'/tmp/browser/lt/home2.png'});
console.log('errors', errs);
await b.close();
