import { Helmet } from "react-helmet-async";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { useState, useRef } from "react";
import { Download, FileText, Loader2, Search, Printer } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export default function TradeTearsheets() {
  const { user } = useAuth();
  const [search, setSearch] = useState("");
  const [selectedProduct, setSelectedProduct] = useState<any>(null);
  const printRef = useRef<HTMLDivElement>(null);

  const { data: products = [], isLoading } = useQuery({
    queryKey: ["tearsheet-products"],
    queryFn: async () => {
      const { data } = await supabase
        .from("trade_products")
        .select("*")
        .eq("is_active", true)
        .order("brand_name")
        .order("product_name");
      return data || [];
    },
  });

  const filtered = products.filter((p: any) =>
    !search || [p.product_name, p.brand_name].some((f: string) => f?.toLowerCase().includes(search.toLowerCase()))
  );

  const handlePrint = () => {
    if (!printRef.current) return;
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`
      <html><head><title>Tearsheet - ${selectedProduct.product_name}</title>
      <style>
        body { font-family: 'Helvetica Neue', sans-serif; margin: 40px; color: #1a1a1a; }
        .header { border-bottom: 1px solid #e5e5e5; padding-bottom: 16px; margin-bottom: 24px; }
        .brand { font-size: 11px; text-transform: uppercase; letter-spacing: 0.15em; color: #666; }
        .name { font-size: 24px; margin: 4px 0 0; }
        .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; }
        .label { font-size: 10px; text-transform: uppercase; letter-spacing: 0.1em; color: #999; margin-bottom: 2px; }
        .value { font-size: 14px; }
        .img { max-width: 100%; max-height: 300px; object-fit: contain; border: 1px solid #eee; }
        .footer { margin-top: 40px; border-top: 1px solid #e5e5e5; padding-top: 16px; font-size: 10px; color: #999; }
      </style></head><body>
      <div class="header">
        <p class="brand">${selectedProduct.brand_name}</p>
        <h1 class="name">${selectedProduct.product_name}</h1>
      </div>
      ${selectedProduct.image_url ? `<img class="img" src="${selectedProduct.image_url}" />` : ""}
      <div class="grid" style="margin-top:24px">
        <div><p class="label">Category</p><p class="value">${selectedProduct.category || "—"}</p></div>
        <div><p class="label">Dimensions</p><p class="value">${selectedProduct.dimensions || "—"}</p></div>
        <div><p class="label">Materials</p><p class="value">${selectedProduct.materials || "—"}</p></div>
        <div><p class="label">Lead Time</p><p class="value">${selectedProduct.lead_time || "—"}</p></div>
        ${selectedProduct.description ? `<div style="grid-column:1/3"><p class="label">Description</p><p class="value">${selectedProduct.description}</p></div>` : ""}
      </div>
      <div class="footer">
        <p>Generated by Maison Affluency Trade Portal · ${new Date().toLocaleDateString()}</p>
      </div>
      </body></html>
    `);
    win.document.close();
    win.print();
  };

  return (
    <>
      <Helmet><title>Tearsheet Builder — Trade Portal</title></Helmet>
      <div className="max-w-6xl space-y-6">
        <div>
          <h1 className="font-display text-2xl text-foreground">Tearsheet Builder</h1>
          <p className="font-body text-sm text-muted-foreground mt-1">
            Generate one-click product tearsheets with specs, dimensions, and pricing for client handoff.
          </p>
        </div>

        {selectedProduct ? (
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <Button variant="ghost" size="sm" onClick={() => setSelectedProduct(null)}>← Back to products</Button>
              <Button variant="outline" size="sm" onClick={handlePrint}><Printer className="h-4 w-4 mr-2" />Print Tearsheet</Button>
            </div>
            <div ref={printRef} className="border border-border rounded-lg p-6 space-y-6">
              <div className="border-b border-border pb-4">
                <p className="font-body text-[10px] uppercase tracking-[0.15em] text-muted-foreground">{selectedProduct.brand_name}</p>
                <h2 className="font-display text-xl text-foreground mt-1">{selectedProduct.product_name}</h2>
              </div>
              {selectedProduct.image_url && (
                <img src={selectedProduct.image_url} alt={selectedProduct.product_name} className="max-h-72 object-contain border border-border rounded" />
              )}
              <div className="grid grid-cols-2 gap-4">
                {[
                  ["Category", selectedProduct.category],
                  ["Dimensions", selectedProduct.dimensions],
                  ["Materials", selectedProduct.materials],
                  ["Lead Time", selectedProduct.lead_time],
                ].map(([label, val]) => (
                  <div key={label}>
                    <p className="font-body text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p>
                    <p className="font-body text-sm text-foreground mt-0.5">{val || "—"}</p>
                  </div>
                ))}
              </div>
              {selectedProduct.description && (
                <div>
                  <p className="font-body text-[10px] uppercase tracking-wider text-muted-foreground">Description</p>
                  <p className="font-body text-sm text-muted-foreground mt-1">{selectedProduct.description}</p>
                </div>
              )}
              <div className="border-t border-border pt-4">
                <p className="font-body text-[10px] text-muted-foreground">Generated by Maison Affluency Trade Portal · {new Date().toLocaleDateString()}</p>
              </div>
            </div>
          </div>
        ) : (
          <>
            <div className="relative max-w-sm">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search products..." className="pl-10 font-body text-sm" />
            </div>
            {isLoading ? (
              <div className="flex justify-center py-20"><Loader2 className="h-5 w-5 animate-spin text-muted-foreground" /></div>
            ) : filtered.length === 0 ? (
              <div className="text-center py-20 border border-dashed border-border rounded-lg">
                <FileText className="h-10 w-10 mx-auto text-muted-foreground/40 mb-3" />
                <p className="font-body text-sm text-muted-foreground">No products found.</p>
              </div>
            ) : (
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
                {filtered.map((p: any) => (
                  <button
                    key={p.id}
                    onClick={() => setSelectedProduct(p)}
                    className="group flex items-start gap-3 p-4 rounded-lg border border-border hover:border-foreground/30 bg-card text-left transition-all hover:shadow-sm"
                  >
                    <div className="w-16 h-16 rounded bg-muted overflow-hidden shrink-0">
                      {p.image_url ? (
                        <img src={p.image_url} alt="" className="w-full h-full object-cover" loading="lazy" />
                      ) : (
                        <div className="w-full h-full flex items-center justify-center"><FileText className="h-5 w-5 text-muted-foreground/30" /></div>
                      )}
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="font-display text-sm text-foreground truncate">{p.product_name}</p>
                      <p className="font-body text-[11px] text-muted-foreground">{p.brand_name}</p>
                      <p className="font-body text-[10px] text-muted-foreground/70 mt-1 capitalize">{p.category}</p>
                    </div>
                  </button>
                ))}
              </div>
            )}
          </>
        )}
      </div>
    </>
  );
}
