
UPDATE designer_curator_picks SET description = 'The Upholstered Back 3-Seater Sofa, designed in 1932 by Jean-Michel Frank, epitomises the radical restraint that made Frank the most influential decorator of the interwar period. Constructed from varnished solid oak with hand-stitched leather upholstery, its deliberately unadorned silhouette channels the pared-back elegance of his legendary commissions for the Vicomte de Noailles and Nelson Rockefeller. The deeply cushioned back and generous proportions deliver exceptional comfort without conceding an ounce of decorative excess. Re-edited by Ecart Paris — the maison founded by Andrée Putman to preserve Frank''s legacy — each sofa is produced to original specifications in France. Also available as a 2-seater (L 160 × P 89 × H 81 cm).' WHERE id = 'a21f9847-b71e-4f4f-abcc-856c0313b584';

UPDATE designer_curator_picks SET description = 'The Croisillon Lamp, conceived in 1924, is among the earliest surviving designs by Jean-Michel Frank and a cornerstone of his lighting oeuvre. A cruciform base in varnished solid oak supports a slender patinated brass stem crowned by a hand-sewn cotton shade, creating an interplay of natural warmth and metallic lustre that prefigures Frank''s later collaborations with Alberto Giacometti. At once sculptural and functional, its compact silhouette (Ø 34 × H 51 cm) suits bedside tables and writing desks alike. Faithfully re-edited by Ecart Paris, the lamp is also available with a solid walnut, golden brass, or black patinated brass base.' WHERE id = 'd423e61c-baac-4e9e-af3d-f80b82b6726a';

UPDATE designer_curator_picks SET description = 'The Soleil Coffee Table, designed circa 1930, is arguably Jean-Michel Frank''s most celebrated decorative object. Its circular top in straw marquetry radiates outward in a precise sunburst pattern — a virtuoso display of the craft technique that Frank elevated from humble origins to the drawing rooms of Parisian haute société. Each strand of rye straw is hand-split, dyed, and inlaid by master artisans, producing subtle tonal variations that shift with ambient light. At Ø 85 × H 35 cm, the table commands attention without dominating the room, embodying Frank''s belief that luxury lies in refined materials rather than ostentatious form. Re-edited by Ecart Paris under exacting standards.' WHERE id = 'b8b26623-7d10-49f4-9046-8fa9d6685f8a';

UPDATE designer_curator_picks SET description = 'Designed in 1939, the Elephant Armchair is Jean-Michel Frank''s final and most generous seating design, named for its broad, embracing silhouette. The smooth solid oak frame cradles a deeply upholstered seat and back, balancing monumental scale with an inviting sense of intimacy. Its wide, gently curved armrests and low centre of gravity make it as suited to a library as to a living room. Re-edited by Ecart Paris in a range of premium fabrics, the chair is also available in various oak and walnut finishes on request — allowing each piece to be tailored to the character of its interior.' WHERE id = '1b6a0347-30e3-41e0-a464-5cc998bf6ce6';

UPDATE designer_curator_picks SET description = 'The Round Table, designed in 1935 by Jean-Michel Frank, showcases the designer''s mastery of oak marquetry at its most architectural. The expansive Ø 150 cm top is assembled from sandblasted oak in a geometric radiating pattern that evokes both Art Deco precision and a naturalistic warmth. Deep sandblasting reveals the grain''s tactile relief, transforming flat timber into a sculptural surface. Originally conceived for a private Parisian dining room, the table seats six comfortably while maintaining the proportional harmony Frank demanded of every commission. Faithfully re-edited by Ecart Paris.' WHERE id = '204350c5-805a-4a5a-a59f-385f608ffb2d';

UPDATE designer_curator_picks SET description = 'The X Stool, designed in 1934, distills Jean-Michel Frank''s design philosophy into its most essential form: two pairs of crossed legs in sandblasted varnished oak, connected by a round seat upholstered in foal hide. The X-frame references both classical curule seats and Japanese joinery, while the tactile contrast between the rough-hewn oak and the supple hide creates a sensory richness that belies the stool''s apparent simplicity. At Ø 55 × H 43 cm, it functions as additional seating, a bedside perch, or a sculptural accent. Re-edited by Ecart Paris to original 1934 specifications.' WHERE id = 'e5f9dfaa-20d3-4a64-a3ff-e6c2edd40f45';
