UPDATE public.designers
SET
  founder = 'Mr. Barbier',
  philosophy = 'Veronese exists to fuse the centuries-old traditions of Murano glassmaking with the spirit of modern French design. Just as Paolo Veronese''s painted vase inspired glassblowers to bring art into life four centuries on, the House believes in influencing art with art — challenging Murano''s masters to explore new ideas, materials and forms while honouring the island''s ancestral savoir-faire.',
  biography = 'The House of Veronese was founded in Paris in 1931, at the height of the decorative arts era, by Mr. Barbier — a passionate devotee of the decorative arts who recognised glassblowing as the ideal medium for the 1930s appetite for exclusive modern design. He named the house after Paolo Veronese, the Renaissance painter whose rendition of a glass vase in "The Annunciation" inspired Murano glassblowers, some four hundred years later, to actually create it. That interplay between art and craft remains the house''s founding idea: luxury Murano glass lighting and mirrors, finely crafted in the tradition of French design.

In its early years Veronese worked hand in hand with André Arbus, a leading figure of 20th-century decorative arts, whose love of luxurious materials and refreshed Neoclassicism made him a natural partner. Together they furnished the mansions, ocean liners and landmark buildings of Arbus''s commissions: the monumental Cascade chandelier of 1938 for Ms. Peterson''s residence, the Murano glass ceilings of the Provence liner''s dining room and cabins in 1951, the coffered ceiling and obelisks of the Bretagne liner in 1952, and the celebrated "Jets d''eau" chandelier for Arbus''s own mansion.

From the late 1970s, Veronese carried Parisian design excellence in Murano glass to an international stage, delivering significant commissions with world-renowned architects across Africa, the Middle East and Europe — hotels, royal palaces, restaurants and landmark public buildings alike.

After sixty years of collaboration with architects, the house opened a new chapter in 2000 with its first Veronese collection, working with internationally acclaimed designers including Chantal Thomass, Hilton McConnico, Olivier Gagnère, Maurizio Galante and Tal Lancman. Veronese brings its Murano expertise and long-standing relationships with the island''s master glassmakers; the designers bring fresh creative energy. Today the house continues Barbier''s founding vision — the fusion of Murano tradition with French design — while constantly seeking new talent and new materials to push the craft forward.',
  notable_works = 'Cascade chandelier (1938, with André Arbus). Murano glass ceilings for the Provence ocean liner (1951). Coffered ceiling and obelisks for the Bretagne liner (1952). "Jets d''eau" chandelier for André Arbus''s mansion. Luxury Murano glass lighting and mirror collections with Chantal Thomass, Hilton McConnico, Olivier Gagnère, Maurizio Galante and Tal Lancman. Bespoke commissions for royal palaces, hotels and landmark buildings worldwide. Founded in Paris, 1931.'
WHERE slug = 'veronese';