export type RosterEntry = { name: string; specialty: string };

// Auto-generated from public.designers where is_published=true. Regenerate with
// scripts/build-public-concierge-roster.ts. This is the deterministic grounding
// list for concierge-public-stream — the model is instructed to only cite names
// from here.
export const ROSTER: readonly RosterEntry[] = [
  {"name": "Adrien Messié", "specialty": "Furniture Design"},
  {"name": "Alex Proba", "specialty": "Contemporary rugs, textiles"},
  {"name": "Alexander Lamont", "specialty": "Artisan Furniture & Luxury Craftsmanship"},
  {"name": "Alinea", "specialty": "Stone Furniture & Design Objects"},
  {"name": "Alpange", "specialty": "The Height of Acoustic Excellence"},
  {"name": "Andrea Claire Studio", "specialty": "Sculptural Lighting"},
  {"name": "Andrée Putman", "specialty": "Interior Design & Furniture"},
  {"name": "Angelo Lelii", "specialty": "Lighting design pioneer, founder of Arredoluce"},
  {"name": "Anthony Guerrée", "specialty": "Furniture Design"},
  {"name": "Apparatus", "specialty": "Contemporary Lighting & Industrial Design"},
  {"name": "Arredoluce", "specialty": "Italian Mid-Century Lighting re-edition"},
  {"name": "Arthur Arbesser", "specialty": "Fashion & Product Design"},
  {"name": "Articolo Studios", "specialty": "Lighting"},
  {"name": "Atelier BdM", "specialty": "Ébénisterie d'Art & Sacred Art Furniture"},
  {"name": "Atelier Demichelis", "specialty": "Limited Edition Lighting & Artisan Craftsmanship"},
  {"name": "Atelier Février", "specialty": "Hand-Knotted Rugs & Textile Art"},
  {"name": "Atelier Pendhapa", "specialty": "Collectible Furniture & Architecture"},
  {"name": "Autoban", "specialty": "Architecture & Design"},
  {"name": "Based Upon", "specialty": "Sculptural Furniture"},
  {"name": "Bec Brittain", "specialty": "Lighting & Jewelry Design"},
  {"name": "Bethan Gray", "specialty": "Contemporary rugs, textiles"},
  {"name": "Bethan Laura Wood", "specialty": "Contemporary rugs, textiles, hand-knotted carpets"},
  {"name": "Bieke Casteleyn", "specialty": "Organic shapes, unconventional thinking, handcrafted in Belgium."},
  {"name": "Bina Baitel", "specialty": "Product Design & Sculptural Objects"},
  {"name": "Bruno Moinard", "specialty": "Interior architecture · Luxury retail · Hospitality · Furniture design"},
  {"name": "Bruno Moinard Editions", "specialty": "Furniture · Lighting · Objects · Interior architecture"},
  {"name": "Caroline Scholl", "specialty": "Interior & Furniture Design"},
  {"name": "Cassina", "specialty": "Contemporary rugs, textiles"},
  {"name": "Cazes & Conquet", "specialty": "Interior Architecture · Brand Strategy · Furniture Design"},
  {"name": "CC-Tapis", "specialty": "Hand-Knotted Rugs · Textile Art · Collectible Design"},
  {"name": "Celso de Lemos", "specialty": "Luxury Textiles & Linens"},
  {"name": "Charles Kalpakian", "specialty": "Product & Furniture Design"},
  {"name": "Charles-Antoine Chappuis", "specialty": "Contemporary rugs, textiles"},
  {"name": "Charlotte Perriand", "specialty": "Contemporary rugs, textiles"},
  {"name": "Chiara Andreatti", "specialty": "Contemporary rugs, textiles, hand-knotted carpets"},
  {"name": "Christophe Delcourt", "specialty": "Furniture Design & Publishing"},
  {"name": "Christopher Boots", "specialty": "Sculptural Design"},
  {"name": "Claude Cartier Studio", "specialty": "Contemporary rugs, textiles"},
  {"name": "Cluzel Pluchon", "specialty": "Furniture Design"},
  {"name": "Collection Particulière", "specialty": "Objects that outlive their purpose"},
  {"name": "Cristina Celestino", "specialty": "Contemporary rugs, textiles, hand-knotted carpets"},
  {"name": "Cristián Mohaded", "specialty": "Furniture & Textile Design"},
  {"name": "Cristoforo Trapani", "specialty": "Product Design"},
  {"name": "Dagmar London", "specialty": "Timeless Scandinavian Design"},
  {"name": "Damien Langlois-Meurinne", "specialty": "Interior Design · Furniture · Residential"},
  {"name": "Dan Yeffet", "specialty": "Glass and lighting design"},
  {"name": "David & Nicolas", "specialty": "Furniture & Object Design"},
  {"name": "De La Espada", "specialty": "Humble hands. Poetic forms. Deeply human."},
  {"name": "De Troupe", "specialty": "Niche lighting and furniture brand"},
  {"name": "Delcourt Collection", "specialty": "Every room, a stage. Every piece, a character."},
  {"name": "Destroyers Builders", "specialty": "Contemporary rugs, textiles"},
  {"name": "Didier Gomez", "specialty": "Interior design and furniture"},
  {"name": "Doshi Levien", "specialty": "Contemporary rugs, textiles"},
  {"name": "Duccio Maria Gambi", "specialty": "Contemporary rugs, textiles"},
  {"name": "Ecart", "specialty": "Re-editions of iconic 20th century furniture and lighting"},
  {"name": "Edoardo Piermattei", "specialty": "Contemporary rugs, textiles"},
  {"name": "Eileen Gray", "specialty": "Architecture & Furniture Design"},
  {"name": "Eligo Studio", "specialty": "Contemporary rugs, textiles"},
  {"name": "Emmanuel Babled", "specialty": "Sculptural Glass & Marble Design"},
  {"name": "Emmanuel Levet Stenne", "specialty": "Alabaster Lighting & Sculptural Fixtures"},
  {"name": "Emmanuelle Simon", "specialty": "Furniture Design, Interior Design"},
  {"name": "Entrelacs", "specialty": "Handcrafted French bronze"},
  {"name": "Eny Lee Parker", "specialty": "Contemporary rugs, textiles"},
  {"name": "Eric Schmitt Studio", "specialty": "Primitive bronze. Sculptural silence."},
  {"name": "Exercice", "specialty": "Furniture Design"},
  {"name": "Fabrice Ausset", "specialty": "Sculpture & Design"},
  {"name": "Fabrice Juan", "specialty": "Furniture & Object Design"},
  {"name": "Faye Toogood", "specialty": "Contemporary rugs, textiles, hand-knotted carpets"},
  {"name": "Federico Pepe", "specialty": "Contemporary rugs, textiles"},
  {"name": "Federico Peri", "specialty": "Architecture & Furniture Design"},
  {"name": "Felix Agostini", "specialty": "Figural Bronze Lighting & Decorative Objects"},
  {"name": "Ferréol Babin", "specialty": "Product & Furniture Design"},
  {"name": "Flavien Delbergue", "specialty": "Furniture & Object Design"},
  {"name": "Forest & Giaconia", "specialty": "Contemporary Furniture & Lighting Design"},
  {"name": "Formafantasma", "specialty": "Contemporary rugs, textiles"},
  {"name": "Francesco Balzano", "specialty": "Furniture Design"},
  {"name": "François Champsaur", "specialty": "Architecture & Interior Design"},
  {"name": "Fredie Jochimek", "specialty": "Glass and lighting design"},
  {"name": "Félix Aublet", "specialty": "Furniture design, lighting, interior architecture"},
  {"name": "Garnier & Linker", "specialty": "Rare materials. Pure forms. Sculptural soul."},
  {"name": "Garth Roberts", "specialty": "Contemporary rugs, textiles"},
  {"name": "Gaëlle Lauriot-Prévost & Dominique Perrault", "specialty": "Architecture & Design"},
  {"name": "Germans Ermičs", "specialty": "Contemporary rugs, textiles"},
  {"name": "Gilles & Boissier", "specialty": "Decorative Object"},
  {"name": "Giuseppe Di Costanzo", "specialty": "Contemporary rugs, textiles"},
  {"name": "Glenn Sestig", "specialty": "Architecture & Interior Design"},
  {"name": "Gounot & Jähnke", "specialty": "Lighting Design"},
  {"name": "Gucci", "specialty": "Contemporary rugs, textiles"},
  {"name": "Haddou & Dufourcq", "specialty": "Architecture & Interior Design"},
  {"name": "Hall Haus", "specialty": "Furniture Design"},
  {"name": "Hamrei", "specialty": "Whimsical Furniture & Collectible Design"},
  {"name": "Haymann Editions", "specialty": "Lighting"},
  {"name": "Hervé van der Straeten", "specialty": "Bronze Sculpture & Lighting Design"},
  {"name": "Herzog & de Meuron", "specialty": "Architecture & Design"},
  {"name": "Hilton McConnico", "specialty": "Glass art and lighting"},
  {"name": "Hom Le Xuan", "specialty": "Decorative Object"},
  {"name": "Humbert & Poyet", "specialty": "Architecture & Interior Design"},
  {"name": "Hélène Paoli", "specialty": "Interior & Furniture Design"},
  {"name": "Iksel", "specialty": "Panoramic Wallcoverings · Decorative Arts · Bespoke Interiors"},
  {"name": "India Mahdavi", "specialty": "Contemporary rugs, textiles, hand-knotted carpets"},
  {"name": "Ionna Vautrin", "specialty": "Product & Furniture Design"},
  {"name": "Isabelle Music", "specialty": "Furniture & Lighting Design"},
  {"name": "Isabelle Stanislas", "specialty": "Architecture & Interior Design"},
  {"name": "Ivan Colominas", "specialty": "Industrial & Product Design"},
  {"name": "Jacob Hashimoto Studio", "specialty": "Decorative Object"},
  {"name": "Jacopo Simonetti", "specialty": "Product Design"},
  {"name": "Jan Kath", "specialty": "Rugs & Textiles"},
  {"name": "Jason Miller", "specialty": "Furniture & Lighting Design"},
  {"name": "Jean-Louis Deniot", "specialty": "Interior & Furniture Design"},
  {"name": "Jean-Marie Massaud", "specialty": "Contemporary rugs, textiles"},
  {"name": "Jean-Michel Frank", "specialty": "Minimalist Luxury & Art Deco Pioneer"},
  {"name": "Jean-Michel Wilmotte", "specialty": "Architecture & Design"},
  {"name": "Jean-Pierre Tortil", "specialty": "Furniture Design"},
  {"name": "Jeremy Maxwell Wintrebert", "specialty": "Freehand Glassblown Lights & Sculptures"},
  {"name": "Jindrich Halabala", "specialty": "Mid-Century Modern · Furniture Design · Tubular Steel"},
  {"name": "Jonah Takagi", "specialty": "Furniture & Product Design"},
  {"name": "Joris Poggioli", "specialty": "Furniture Design"},
  {"name": "Joseph Dirand", "specialty": "Architecture & Interior Design"},
  {"name": "Julien Scarbonchi", "specialty": "Furniture & Object Design"},
  {"name": "Karen Chekerdjian", "specialty": "Furniture & Product Design"},
  {"name": "Kerstens", "specialty": "Architectural Furniture & Objects"},
  {"name": "Khaki Kroener", "specialty": "Furniture & Lighting Design"},
  {"name": "Kiko Lopez", "specialty": "Artisan Mirrors & Reflective Surfaces"},
  {"name": "Kwangho Lee", "specialty": "Contemporary rugs, textiles, hand-knotted carpets"},
  {"name": "La Chance", "specialty": "A cosmopolitan selection of the finest designers"},
  {"name": "Laurence Brabant", "specialty": "Glass sculpture and lighting"},
  {"name": "Laurent Maugoust & Cécile Chenais", "specialty": "Interior architecture, furniture design"},
  {"name": "Lazzarini & Pickering", "specialty": "Architecture & Furniture Design"},
  {"name": "Le Berre Vevaud", "specialty": "Eclectic interiors crafted like Haute Couture"},
  {"name": "Leo Sentou", "specialty": "Contemporary Classicist Furniture Design"},
  {"name": "Leonardo Talarico", "specialty": "Contemporary rugs, textiles"},
  {"name": "Lorenzo Zaccarin", "specialty": "Product Design"},
  {"name": "Lost Profile Studio", "specialty": "Lighting"},
  {"name": "Luca Erba", "specialty": "Furniture Design"},
  {"name": "Luca Nichetto", "specialty": "Product & Industrial Design"},
  {"name": "Lucie Koldova", "specialty": "Furniture & Lighting Design"},
  {"name": "Luke Edward Hall", "specialty": "Contemporary rugs, textiles"},
  {"name": "M. Galante & T. Lancman", "specialty": "Glass and lighting design"},
  {"name": "Maarten De Ceulaer", "specialty": "Contemporary rugs, textiles"},
  {"name": "Maarten Vrolijk", "specialty": "Contemporary Handblown Glass Art & Sculptural Vessels"},
  {"name": "Made in Kira - Roman Frankel", "specialty": "Japanese poetry, refined in light."},
  {"name": "Mae Engelgeer", "specialty": "Contemporary rugs, textiles, hand-knotted carpets"},
  {"name": "Maison Charles", "specialty": "Bronze Lighting & Decorative Objects"},
  {"name": "Maison Matisse", "specialty": "Contemporary rugs, textiles"},
  {"name": "Maison WeCraft", "specialty": ""},
  {"name": "Man of Parts", "specialty": "Curated Contemporary Furniture Collections"},
  {"name": "Manuel Aires Mateus", "specialty": "Architecture & Design"},
  {"name": "Marcantonio Brandolini D'Adda", "specialty": "Glass Art & Sculptural Vessels"},
  {"name": "Marco De Vincenzo", "specialty": "Contemporary rugs, textiles"},
  {"name": "Mariano Fortuny", "specialty": "Textile, Lighting & Fashion Design"},
  {"name": "Marléne Huissoud", "specialty": "Contemporary rugs, textiles"},
  {"name": "Marta Sala Éditions", "specialty": ""},
  {"name": "Martin Massé", "specialty": "Classical architecture lines, handcrafted into collectibles."},
  {"name": "Martino Gamper", "specialty": "Contemporary rugs, textiles"},
  {"name": "Maryna Dague & Nathan Baraness", "specialty": "Interior & Furniture Design"},
  {"name": "Massimo Giorgetti", "specialty": "Contemporary rugs, textiles"},
  {"name": "Matteo Cibic", "specialty": "Product & Interior Design"},
  {"name": "Matthew Hilton", "specialty": "Furniture Design"},
  {"name": "Matthieu Gicquel", "specialty": "French by hand. Mineral by nature. Wabi-sabi at heart."},
  {"name": "Matéo Garcia", "specialty": "Furniture Design"},
  {"name": "Mernøe", "specialty": "Bespoke Lighting · Danish Craftsmanship · Sculptural Design"},
  {"name": "Michel Amar Studio", "specialty": "Interior Design"},
  {"name": "Michel Boyer", "specialty": "French architecture. Modern institution."},
  {"name": "Michel Jouannet", "specialty": "Furniture & Metalwork Design"},
  {"name": "Michele Chiossi", "specialty": "Sculpture & Design"},
  {"name": "Milan Pekař", "specialty": "Czech alchemy. Crystalline beauty."},
  {"name": "Milena Denis Polania", "specialty": "Furniture & Object Design"},
  {"name": "MMairo", "specialty": "Sculpting nature, the Italian way."},
  {"name": "Muller Van Severen", "specialty": "Contemporary rugs, textiles"},
  {"name": "Nathalie Ziegler", "specialty": "Dancing light, captured in magical glass."},
  {"name": "Neri & Hu", "specialty": "Architecture & Design"},
  {"name": "Nicolas Aubagnac", "specialty": "Classicism of the Future"},
  {"name": "Niko Koronis", "specialty": "Architecture & Product Design"},
  {"name": "Noom", "specialty": "Modern minimalism. Ukrainian essence."},
  {"name": "Note Design Studio", "specialty": "Product & Furniture Design"},
  {"name": "Noé Duchaufour-Lawrance", "specialty": "Organic forms. Fluid nature. Sculptural soul."},
  {"name": "OA London", "specialty": "Interior & Furniture Design"},
  {"name": "Objects of Common Interest", "specialty": "Contemporary rugs, textiles"},
  {"name": "Odd Matter", "specialty": "Contemporary rugs, textiles"},
  {"name": "OKHA", "specialty": "Collectible Furniture & Contemporary African Design"},
  {"name": "Okurayama Studio", "specialty": "Sculptural Furniture"},
  {"name": "Olivia Cognet", "specialty": "Ceramic Artist & Designer"},
  {"name": "Olivier Gagnère", "specialty": "Glass and furniture design"},
  {"name": "oOumm", "specialty": "Decorative Object"},
  {"name": "Ornella Mei", "specialty": "Furniture & Object Design"},
  {"name": "Osanna Visconti", "specialty": "Nature immortalized in bronze"},
  {"name": "Osvaldo Tenório", "specialty": "Furniture & Object Design"},
  {"name": "Overgaard & Dyrman", "specialty": "Two friends. One craft. Entirely Danish."},
  {"name": "Ozone", "specialty": "Bronze furniture and lighting editions"},
  {"name": "P.A.M.", "specialty": "Contemporary rugs, textiles"},
  {"name": "Parisotto + Formenton", "specialty": "Contemporary rugs, textiles"},
  {"name": "Parsa Editions", "specialty": "Contemporary design editions"},
  {"name": "Patricia Urquiola", "specialty": "Contemporary rugs, textiles, hand-knotted carpets"},
  {"name": "Patrick E. Naggar", "specialty": "Furniture and lighting design"},
  {"name": "Patrick Jouin", "specialty": "Industrial and lighting design"},
  {"name": "Paul László", "specialty": "Where modern design becomes cinematic."},
  {"name": "Pauline Deltour", "specialty": "Product & Industrial Design"},
  {"name": "Peter Reed 1861", "specialty": "Luxury Bed Linen · British Heritage Textiles"},
  {"name": "Philippe Malouin", "specialty": "Contemporary rugs, textiles"},
  {"name": "Piero Manara", "specialty": "Furniture & Lighting Design"},
  {"name": "Pierre Augustin Rose", "specialty": "Sculptural Furniture & Lighting"},
  {"name": "Pierre Bonnefille", "specialty": "Patinated surfaces, Bronze Paintings & Metamorphosis furniture"},
  {"name": "Pierre Chareau", "specialty": "Radical light. Industrial modernism."},
  {"name": "Pierre Favresse", "specialty": "Furniture & Object Design"},
  {"name": "Pierre Frey", "specialty": "Textiles · Wallcoverings · French Heritage Fabrics"},
  {"name": "Pierre Paulin", "specialty": "Furniture & Industrial Design"},
  {"name": "Pierre-Yves Rochon", "specialty": "Interior design and lighting"},
  {"name": "Piet Hein Eek", "specialty": "Furniture and lighting design"},
  {"name": "Pinton 1867", "specialty": "Rugs & Tapestry"},
  {"name": "Poltrona Frau", "specialty": "Luxury Leather Seating · Italian Craftsmanship"},
  {"name": "Pool Studio", "specialty": "Furniture Design"},
  {"name": "Pouenat", "specialty": "Uniquely French. Handcrafted in metal."},
  {"name": "Privatiselectionem", "specialty": "Furniture"},
  {"name": "Raphael Navot", "specialty": "Architecture and lighting design"},
  {"name": "Reda Amalou", "specialty": "Refined by architecture. Enriched by the world."},
  {"name": "Refractory Studio", "specialty": "Lighting"},
  {"name": "Regular Company", "specialty": "Furniture & Product Design"},
  {"name": "Roberto Sironi", "specialty": "Contemporary rugs, textiles"},
  {"name": "Robicara", "specialty": "Italian-crafted Luxury Furniture"},
  {"name": "Rodolphe Parente", "specialty": "Architecture & Interior Design"},
  {"name": "Rooms Studio", "specialty": "Contemporary rugs, textiles"},
  {"name": "Rop van Mierlo", "specialty": "Contemporary rugs, textiles"},
  {"name": "RoWin' Atelier — Rochette Frederic & Winkler Hervé", "specialty": "Artisan Ceramics & Sculptural Objects"},
  {"name": "Régis Botta", "specialty": "Architecture & Lighting Design"},
  {"name": "Sabine Marcelis", "specialty": "Contemporary rugs, textiles"},
  {"name": "Sacha Walckhoff", "specialty": "Furniture & Fashion Design"},
  {"name": "Saint-Louis", "specialty": "French artisanal crystal since 1586"},
  {"name": "Sam Accoceberry", "specialty": "Hand-carved alabaster lighting"},
  {"name": "Sam Baron", "specialty": "Art & Design"},
  {"name": "Scarlett Rouge", "specialty": "Contemporary rugs, textiles"},
  {"name": "Sebastian Herkner", "specialty": "Product & Furniture Design"},
  {"name": "Serge Mouille", "specialty": "Lighting"},
  {"name": "Sergej Kirilov", "specialty": ""},
  {"name": "Services Généraux", "specialty": "Furniture Design"},
  {"name": "Simon Cabrol", "specialty": "Storage"},
  {"name": "Sollen", "specialty": "French furniture editor — collectible seating, tables and lighting"},
  {"name": "Steven Holl", "specialty": "Contemporary rugs, textiles"},
  {"name": "Studio Anansi", "specialty": "Furniture Design"},
  {"name": "Studio BrichetZiegler", "specialty": "Furniture Design"},
  {"name": "Studio Evidens ex Borella Art Design", "specialty": "Furniture & Sculpture"},
  {"name": "Studio Klass", "specialty": "Contemporary rugs, textiles"},
  {"name": "Studio Parisien", "specialty": "Interior & Furniture Design"},
  {"name": "Studio Piet Boon", "specialty": "Contemporary rugs, textiles"},
  {"name": "Studioformart", "specialty": "Architecture & Design"},
  {"name": "Studioilse", "specialty": "Interior & Furniture Design"},
  {"name": "Studiopepe", "specialty": "Contemporary rugs, textiles"},
  {"name": "Stéphane CG", "specialty": "Fine Art Photography · Diasec Prints · Contemporary Art"},
  {"name": "Stéphane Parmentier", "specialty": "Furniture"},
  {"name": "SUNNEI", "specialty": "Contemporary rugs, textiles"},
  {"name": "Sybille de Margerie", "specialty": "Interior & Furniture Design"},
  {"name": "Sé Collections", "specialty": "Seating"},
  {"name": "Taher Asad-Bakhtiari", "specialty": "Contemporary rugs, textiles"},
  {"name": "Takayokaya", "specialty": "Japanese Zabuton · Handcrafted Textiles · Kyoto Heritage"},
  {"name": "Thierry Lemaire", "specialty": "Sensual post-modernism · Sophisticated materiality"},
  {"name": "Thomas Boog", "specialty": "Furniture & Decorative Arts"},
  {"name": "Théophile de Bascher", "specialty": "Furniture Design"},
  {"name": "Théorème Editions", "specialty": "Design Publishing · Limited Editions · French Savoir-Faire"},
  {"name": "Toni Grilo", "specialty": "Furniture & Product Design"},
  {"name": "Toulemonde Bochart", "specialty": "Parisian elegance, handcrafted into every thread"},
  {"name": "Tristan Auer", "specialty": ""},
  {"name": "Univers Uchronia", "specialty": "Contemporary rugs, textiles"},
  {"name": "Valeria Nascimento", "specialty": "Decorative Object"},
  {"name": "Valérie Rostaing", "specialty": "Decorative Object"},
  {"name": "Valérie Serin-Lok", "specialty": "Furniture & Object Design"},
  {"name": "Venelin Kokalov", "specialty": "Product & Furniture Design"},
  {"name": "Veronese", "specialty": "Murano glass lighting and furniture"},
  {"name": "Victoria Magniant", "specialty": ""},
  {"name": "Victoria Wilmotte", "specialty": "Furniture Design, Sculpture"},
  {"name": "Wegener & Masquida", "specialty": "Glass and lighting design"},
  {"name": "Wendy Andreu", "specialty": "Furniture Design"},
  {"name": "Yabu Pushelberg", "specialty": "Interior & Product Design · Hospitality · Furniture"},
  {"name": "Yann Le Coadic", "specialty": "Furniture & Lighting Design"},
  {"name": "Yuri Himuro", "specialty": "Contemporary rugs, textiles"},
  {"name": "Yves Taralon", "specialty": "Glass and lighting design"},
  {"name": "Zanellato/Bortotto", "specialty": "Contemporary rugs, textiles"},
  {"name": "Zaven", "specialty": "Contemporary rugs, textiles"},
] as const;
