// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/search-curator-picks.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { z } from "npm:zod@^3.25.76";
var SITE_ORIGIN = "https://www.maisonaffluency.com";
function getClient() {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, anon, { auth: { persistSession: false, autoRefreshToken: false } });
}
var search_curator_picks_default = defineTool({
  name: "search_curator_picks",
  title: "Search curator picks",
  description: "Search Maison Affluency's public catalog of curator-picked designer furniture, lighting, and collectibles. Filter by free-text query, designer, category, subcategory, or materials. Returns product cards with a deep link back to the product page. Trade pricing is never returned \u2014 every result shows 'Price on Request'.",
  inputSchema: {
    query: z.string().trim().max(200).optional().describe("Free-text query matched against title, subtitle, materials, and tags."),
    designer_slug: z.string().trim().max(120).optional().describe("Restrict to a specific designer by slug."),
    category: z.string().trim().max(80).optional().describe("Top-level category, e.g. 'Seating', 'Lighting', 'Tables'."),
    subcategory: z.string().trim().max(80).optional().describe("Subcategory, e.g. 'Sofa', 'Pendant', 'Console'."),
    material: z.string().trim().max(80).optional().describe("Material substring, e.g. 'bronze', 'walnut'."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results, default 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input) => {
    const supabase = getClient();
    const startedAt = Date.now();
    const logCall = (result_count, is_error = false) => {
      supabase.from("mcp_query_log").insert({
        tool_name: "search_curator_picks",
        args: input,
        result_count,
        is_error,
        duration_ms: Date.now() - startedAt
      }).then(() => {
      }, () => {
      });
    };
    const limit = input.limit ?? 20;
    let designerId = null;
    let designerName = null;
    if (input.designer_slug) {
      const { data: d } = await supabase.from("designers").select("id, name").eq("slug", input.designer_slug).eq("is_published", true).eq("trade_only", false).maybeSingle();
      if (!d) {
        logCall(0);
        return {
          content: [{ type: "text", text: `No public designer found for slug "${input.designer_slug}".` }],
          structuredContent: { results: [], total: 0 }
        };
      }
      designerId = d.id;
      designerName = d.name;
    }
    let q = supabase.from("designer_curator_picks_public").select(
      "id, designer_id, title, subtitle, category, subcategory, materials, dimensions, image_url, tags, lead_time, origin, edition"
    ).eq("is_hidden", false).order("sort_order", { ascending: true, nullsFirst: false }).limit(limit);
    if (designerId) q = q.eq("designer_id", designerId);
    if (input.category) q = q.ilike("category", input.category);
    if (input.subcategory) q = q.ilike("subcategory", input.subcategory);
    if (input.material) q = q.ilike("materials", `%${input.material}%`);
    if (input.query) {
      const like = `%${input.query.replace(/[%_]/g, "")}%`;
      q = q.or(`title.ilike.${like},subtitle.ilike.${like},materials.ilike.${like}`);
    }
    const { data, error } = await q;
    if (error) {
      return {
        content: [{ type: "text", text: `Search failed: ${error.message}` }],
        isError: true
      };
    }
    const ids = Array.from(new Set((data ?? []).map((r) => r.designer_id).filter(Boolean)));
    let designersById = /* @__PURE__ */ new Map();
    if (ids.length) {
      const { data: ds } = await supabase.from("designers").select("id, name, slug").in("id", ids).eq("is_published", true).eq("trade_only", false);
      for (const row of ds ?? []) designersById.set(row.id, { name: row.name, slug: row.slug });
    }
    const results = (data ?? []).map((r) => {
      const designer = r.designer_id ? designersById.get(r.designer_id) : null;
      if (!designer) return null;
      return {
        id: r.id,
        title: r.title,
        subtitle: r.subtitle,
        designer: designer.name,
        designer_slug: designer.slug,
        category: r.category,
        subcategory: r.subcategory,
        materials: r.materials,
        dimensions: r.dimensions,
        edition: r.edition,
        origin: r.origin,
        lead_time: r.lead_time,
        tags: r.tags,
        image_url: r.image_url,
        price: "Price on Request",
        product_url: `${SITE_ORIGIN}/designers/${designer.slug}?pick=${r.id}`
      };
    }).filter((x) => x !== null);
    const summary = results.length === 0 ? `No public curator picks matched${designerName ? ` for ${designerName}` : ""}.` : `Found ${results.length} curator pick${results.length === 1 ? "" : "s"}${designerName ? ` by ${designerName}` : ""}. All prices are Price on Request \u2014 sign in as a trade member on maisonaffluency.com for net pricing and tearsheets.`;
    return {
      content: [{ type: "text", text: summary }],
      structuredContent: { results, total: results.length }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { z as z2 } from "npm:zod@^3.25.76";
var SITE_ORIGIN2 = "https://www.maisonaffluency.com";
function getClient2() {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient2(url, anon, { auth: { persistSession: false, autoRefreshToken: false } });
}
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product",
  description: "Fetch the full public specification for a single curator pick by id: designer, category, materials, dimensions, edition, lead time, gallery images, and a deep link back to the product page. Trade pricing and tearsheet PDFs are never returned \u2014 those require signing in as a trade member on maisonaffluency.com.",
  inputSchema: {
    pick_id: z2.string().uuid().describe("The curator pick id returned by search_curator_picks.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ pick_id }) => {
    const supabase = getClient2();
    const { data, error } = await supabase.from("designer_curator_picks_public").select(
      "id, designer_id, title, subtitle, category, subcategory, materials, materials_description, dimensions, description, edition, edition_number, edition_signing, origin, lead_time, tags, image_url, gallery_images, gallery_captions, photo_credit, is_hidden"
    ).eq("id", pick_id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Lookup failed: ${error.message}` }], isError: true };
    }
    if (!data || data.is_hidden) {
      return {
        content: [{ type: "text", text: "Product not found or not publicly available." }],
        isError: true
      };
    }
    const { data: designer } = await supabase.from("designers").select("id, name, slug, is_published, trade_only").eq("id", data.designer_id).maybeSingle();
    if (!designer || !designer.is_published || designer.trade_only) {
      return {
        content: [{ type: "text", text: "Product not found or not publicly available." }],
        isError: true
      };
    }
    const product = {
      id: data.id,
      title: data.title,
      subtitle: data.subtitle,
      designer: designer.name,
      designer_slug: designer.slug,
      category: data.category,
      subcategory: data.subcategory,
      materials: data.materials,
      materials_description: data.materials_description,
      dimensions: data.dimensions,
      description: data.description,
      edition: data.edition,
      edition_number: data.edition_number,
      edition_signing: data.edition_signing,
      origin: data.origin,
      lead_time: data.lead_time,
      tags: data.tags,
      image_url: data.image_url,
      gallery_images: data.gallery_images ?? [],
      gallery_captions: data.gallery_captions ?? null,
      photo_credit: data.photo_credit,
      price: "Price on Request",
      product_url: `${SITE_ORIGIN2}/designers/${designer.slug}?pick=${data.id}`,
      tearsheet_note: "Tearsheet PDFs and net trade pricing are available only to registered trade members on maisonaffluency.com."
    };
    const text = [
      `${product.title}${product.subtitle ? " \u2014 " + product.subtitle : ""}`,
      `Designer: ${product.designer}`,
      product.category ? `Category: ${product.category}${product.subcategory ? " / " + product.subcategory : ""}` : null,
      product.materials ? `Materials: ${product.materials}` : null,
      product.dimensions ? `Dimensions: ${product.dimensions}` : null,
      product.edition ? `Edition: ${product.edition}` : null,
      product.lead_time ? `Lead time: ${product.lead_time}` : null,
      `Price: Price on Request`,
      `View: ${product.product_url}`
    ].filter(Boolean).join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: { product }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "maison-affluency-catalog",
  title: "Maison Affluency Catalog",
  version: "0.1.0",
  instructions: "Public catalog of collectible design and haute d\xE9cor curated by Maison Affluency. Use `search_curator_picks` to discover pieces by designer, category, subcategory, materials, or free-text query. Use `get_product` to fetch the full public specification for a single curator pick. Prices are always 'Price on Request'; trade net pricing, tearsheet PDFs, and CAD files are available only to signed-in trade members on maisonaffluency.com.",
  tools: [search_curator_picks_default, get_product_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
