UPDATE public.designers SET biography = $bio$Jacob Hashimoto is a Japanese-American artist whose immersive, large-scale installations of hand-crafted paper and bamboo kites have become some of the most recognisable bodies of work in contemporary American art. Born in 1973 in Greeley, Colorado, Hashimoto studied at the School of the Art Institute of Chicago, graduating with a BFA in 1996. He lives and works in Ossining, New York, where his studio produces the thousands of individually painted, screen-printed and assembled kite elements that compose each piece.

Hashimoto's installations layer hundreds — sometimes tens of thousands — of disc- and diamond-shaped kites on fine nylon line, suspending them from ceilings, walls and architectural voids to form pixelated landscapes, clouds and constellations. The work moves fluidly between East Asian craft tradition, American abstraction and the visual language of digital imaging, recalling at once Edo-period woodblock prints, Sol LeWitt grids and the low-resolution geometry of early video games.

<strong>'I'm interested in how images and landscapes are constructed — how a million small parts add up to a single experience. The kite is a unit of light, of memory, of weather.'</strong> — Jacob Hashimoto

Career-defining solo exhibitions include 'Gas Giant' at MOCA Pacific Design Center, Los Angeles (2014); 'Never Comes Tomorrow' at MAK – Museum of Applied Arts, Vienna (2018); 'The Eclipse' at St. Cornelius Chapel, Governors Island, New York (2017), commissioned by Brookfield Place; 'Skyfarm Fortress' at 21c Museum Hotel, Bentonville; and 'Clouds and Chaos' at Sara Hildén Art Museum, Tampere. He represented in the 54th Venice Biennale's Italian Pavilion in 2011 and has shown extensively with Mary Boone Gallery and Miles McEnery Gallery in New York, Rhona Hoffman Gallery in Chicago, Ronchini Gallery in London, Galleria Poggiali in Florence and Pietrasanta, Studio la Città in Verona, and Galerie Forsblom in Helsinki.

His work is held in the permanent collections of the Solomon R. Guggenheim Museum, the Brooklyn Museum, Crystal Bridges Museum of American Art, the Museo del Novecento in Milan, MAK Vienna, the Sara Hildén Art Museum and the Nerman Museum of Contemporary Art, alongside major corporate and private holdings. Architectural and public commissions include monumental installations for MGM Cotai in Macau, The Times Square Edition hotel in New York, Brookfield Place, the Microsoft Collection in Redmond and Yorkshire Sculpture Park.

Hashimoto has been profiled in The New York Times, Artforum, Wallpaper*, Cultured, Surface, Architectural Digest and The Art Newspaper, and his practice has been the subject of monographs published by Hatje Cantz and Skira. He has collaborated with the choreographer Wendy Whelan and the composer David Lang on dance and music projects that extend his visual vocabulary into time-based media.

<strong>Through a practice that treats craft as conceptual material, Jacob Hashimoto has built a singular bridge between Japanese visual tradition, American Minimalism and the screen-based imagery of the digital age — turning the humble kite into an instrument of architectural-scale storytelling.</strong>$bio$
WHERE slug = 'jacob-hashimoto-studio';

UPDATE public.designers SET biography = $bio$Paul Cocksedge is a British designer whose poetic, technically ambitious work has redefined the relationship between sculpture, lighting and public space over the past two decades. Born in London in 1978, he studied product design at Sheffield Hallam University before completing an MA at the Royal College of Art under Ron Arad and Ingo Maurer, the latter of whom invited him to exhibit in Milan immediately after graduation. In 2004 he founded Paul Cocksedge Studio in East London with his partner Joana Pinho; the studio now operates from a purpose-built workshop in Hackney.

Cocksedge grew up in a working-class, multicultural part of North London, in Turnpike Lane, bordering Tottenham. <strong>'When I entered the art and design world, I came in as a bit of an outsider. We weren't visiting the Tate or the Design Museum. So I approached it from a different angle.'</strong>

That outsider's instinct produced a body of work that swings between intimate object and civic-scale intervention. Early lighting pieces such as 'Styrene', 'Bombay Sapphire' and 'Watt?' for Established & Sons established his reputation for material curiosity; subsequent collaborations include Swarovski, Hermès, Issey Miyake, Flos, Moooi, Cappellini, Lasvit, Sony, BMW, Google and Microsoft. He has held a long-standing partnership with Carpenters Workshop Gallery, which represents his sculptural furniture worldwide, including the acclaimed 'Slump' series of mirror-polished bronze and glass tables, 'Vamp' and 'Excavation' — a Milan Design Week installation in which a section of his own studio floor was lifted and cast into furniture before the building was demolished.

Public commissions and large-scale installations include 'Bourrasque' in Trafalgar Square for the London Festival of Architecture; 'Please Be Seated', the undulating public bench unveiled at the London Design Festival in Broadgate; 'Living Staircase' for the Ampersand Building in Soho; 'Freeze' at the V&A Museum; and 'Here Comes the Sun' for Lexus. His work has been commissioned by MoMA, Swire Properties, Selfridges and the City of London, and exhibited at Design Miami, Salone del Mobile and the Triennale di Milano.

Cocksedge's pieces are held in the permanent collections of the Victoria and Albert Museum, the Museum of Modern Art in New York, the Art Institute of Chicago, the MAK in Vienna and the Design Museum, London. His monograph, 'Reflections', was published by Phaidon and accompanied a major survey exhibition at Carpenters Workshop Gallery in London. He has delivered a TED talk on the role of design in public life and lectured at the Royal College of Art, the Architectural Association and Harvard GSD.

Editorial coverage spans Wallpaper*, Dezeen, Architectural Digest, Domus, The Financial Times, The New York Times and Frame, and he has received the Wallpaper* Design Award, the iF Design Award and the Red Dot 'Best of the Best'.

<strong>From Trafalgar Square to the gallery floor, Paul Cocksedge has turned engineering, optics and gravity into instruments of public wonder — making design that asks the viewer to complete the work.</strong>$bio$
WHERE slug = 'paul-cocksedge-studio';