
UPDATE designers SET
  biography = 'Born in 1956 in the coastal town of Dieppe, Normandy, Bruno Moinard was shaped from childhood by the luminous skies, chalk cliffs, and shifting light of the Channel coastline. Drawing and painting became his earliest means of expression — a habit of rapid, gestural sketching that would become his lifelong creative signature.

In 1972 he moved to Paris to study at the École Nationale Supérieure des Arts Appliqués et des Métiers d''Art (Olivier de Serres), graduating in 1978. A chance freelance assignment for Andrée Putman — ''initially hired to execute a few small drawings expected to keep me busy for a few days'' — became a fifteen-year collaboration at Ecart International, where Moinard rose to become creative director. Together they shaped some of the defining interiors of the 1980s: boutiques for Thierry Mugler, Karl Lagerfeld, Azzedine Alaïa, and Balenciaga; the Morgans Hotel in New York; the private apartments of François Mitterrand at the Élysée Palace (alongside Philippe Starck); the interior fitting of five Concordes for Air France; and ministerial offices including that of Culture Minister Jack Lang.

In 1995, Moinard founded his own practice, 4BI, from 41 avenue Montaigne. A pivotal commission came in 2002 when he was appointed architect for the global network of Cartier boutiques — a partnership that has since produced over 470 stores across six continents, from the Champs-Élysées flagship to New Bond Street, Ginza, and Shanghai K11. This long-standing relationship with François Pinault also led to the renovation of Christie''s New York headquarters and the Château Latour estate in Pauillac, including its guest pavilion, offices, and members'' club at the Four Seasons Ten Trinity Square in London.

Moinard''s work across Asia has been particularly extensive. Through the agency he has designed Cartier flagships and boutiques in Shanghai, Beijing, Hong Kong, Macau, Chengdu, Tianjin, Changchun, Xiamen, Qingdao, Suzhou, and Hongqiao Airport, as well as locations in Tokyo, Seoul, Bangkok, and Singapore. Major hospitality commissions in the region include the Diaoyutai-MGM boutique hotels in Chengdu (2013), the Wison corporate headquarters in Shanghai, the Dongqian Lake House in Ningbo, a showroom in Hangzhou, a Tea Salon in Wenzhou, a private residence in Minami-Aoyama Tokyo, the JW Marriott Hotel & Spa in Seoul (2020), the SPA Yunjac at Shinsegae Group Seoul, and, most recently, the Hôtel Capella at Galaxy Macau (2025).

In Europe, his portfolio spans the Plaza Athénée Hotel in Paris — lobby, reception halls, ballroom, La Galerie, Le Relais Plaza, and the Art Déco rooms — the Four Seasons Hotel at Ten Trinity Square and The Grill at The Dorchester in London, the Hotel Cala di Volpe in Sardinia, the Hotel Eden for Dorchester Collection in Rome, the Hôtel du Marc for Veuve Clicquot in Reims, and the Galeries Lafayette department stores in Paris, Strasbourg, Doha, and Dubai. He has also designed headquarters for Hermès, Balenciaga, and TF1, alongside residential commissions spanning Paris, London, Monaco, Brussels, Morocco, and Canada.

In 2007 he was joined by Claire Bétaille, a graduate of the Écoles du Louvre and Camondo, who became his partner in 2012. In 2020 the practice was renamed Moinard-Bétaille, today a forty-five-person studio that Moinard describes as ''a tremendous melting pot, which we combine with top French craftspeople.''

Bruno Moinard Éditions was established in 2014 as a dedicated furniture, lighting, and objects line — translating four decades of architectural sensibility into refined, collectible pieces produced entirely in France with master artisans. The collections are presented at the Rue Jacob flagship and carried in eleven cities including New York, Shanghai, London, Miami, Moscow, and Vancouver.

Moinard received the Silver Medal of the Académie d''Architecture in 2007 and was decorated Chevalier of the Légion d''Honneur in 2010. He has published two monographs: ''L''Architecte Promeneur'' (Éditions La Martinière, 2010) and ''Du Trait à la Lumière'' (2015). Since 2017 he has also exhibited his paintings, first at the Galerie Diane de Polignac in Paris.',
  specialty = 'Interior architecture · Luxury retail · Hospitality · Furniture design',
  notable_works = 'Cartier global boutique network (470+ stores worldwide since 2002). Plaza Athénée Hotel, Paris. Four Seasons Ten Trinity Square, London. Hôtel Capella, Galaxy Macau (2025). Diaoyutai-MGM Hotels, Chengdu. JW Marriott Hotel & Spa, Seoul. Christie''s New York. Château Latour, Pauillac. Hôtel du Marc, Veuve Clicquot, Reims. Bruno Moinard Éditions furniture line (est. 2014).',
  philosophy = 'Travelling architects, ambassadors of French luxury, we seek to invent the heritage of tomorrow.
— Bruno Moinard'
WHERE id = 'f8ba5da1-e45f-45d9-a7ad-68fefc1df006';
