UPDATE public.designers
SET image_url = 'https://dcrauiygaezoduwdjmsm.supabase.co/storage/v1/object/public/assets/designers%2Farnold-madsen%2Fportrait.jpg',
    biography = $bio$Arnold Johan Madsen (1907–1989) was a Danish upholsterer who worked with his hands rather than a drawing board, and whose independence of method produced one of the most distinctive lounge chairs of the twentieth century.

He was born in Sønderlev, in the north of Jutland, one of six children of the shoemaker Mads Madsen and his wife Anna. His father believed that a craftsman's education was the surest inheritance a son could be given, and each of the boys was sent to complete an apprenticeship. Arnold took the longest way round. He first went to sea, then sailed for the United States in 1929, worked there for a year, and came home to Denmark to train as an upholsterer — a trade he chose late and pursued with unusual seriousness.

"My father was a furniture man, and the Muslingstol belonged to him and our family."

By 1941 he was a highly skilled upholsterer in Copenhagen with his own business, A. Madsen Møbelpolst. In 1943 he took a small basement workshop at Gothersgade 158B, a short walk from Rosenborg Castle. His days were spent reupholstering chairs and sofas for private clients: stripping frames, re-tying springs, judging the fill of a seat by hand. It was slow, physical, anonymous work, and under the German occupation and its depressed economy it paid less each year. What it gave him instead was an intimate knowledge of how a chair is actually built — where it carries weight, where it fails, and how a body settles into it.

Madsen had no formal design training. No architecture, no drafting, none of the Academy schooling that shaped his celebrated contemporaries. When he began to experiment with a chair of his own, he did not commit the idea to paper: he hand-formed a full-scale model in plaster, shaping and re-shaping until the volume felt right beneath him. That necessity became his method, and it accounts for the organic ease of everything he made — forms arrived at through material and touch rather than through line.

The breakthrough came in 1944: the Muslingstol, or Clam Chair, drawn from the shape of an open clam shell. Its fluid silhouette, club-shaped legs and simple curved arms answered a new zeitgeist brewing among young Danish designers such as Viggo Boesen, Finn Juhl and Flemming Lassen, as the heavy historical modes of earlier generations gave way to biomorphic forms suited to the modern Danish home.

Finding a cabinetmaker willing to translate plaster into a durable wooden frame proved harder than the design itself. After many refusals he knocked on the door of Winter & Winding, where the foreman was Henry Schubell, a gifted young cabinetmaker one year his senior. Schubell devised a way to join the frame without compromising its shape, distributing weight evenly while keeping the chair sound. His son Flemming later recalled: "The joinery was so difficult to make with just a bandsaw that no one else could do it."

The earliest editions had oak arms and legs fixed to a beech frame with glued dowels and steel bolts, padded with coir fibre and wool felt over jute webbing, and finished with seven rows of deep buttons that pulled the seat into its concave shape. Madsen carried them himself to dealers along Gothersgade and beyond — Olsson Møbler, Illum Bolighus, the newly opened NY FORM — and they sold. In 1945 Schubell left Winter & Winding to join him full time, and the partnership Madsen & Schubell was formally established. The Pragh Chair followed in 1948, a larger and more eccentric cousin of the Clam.

Around 1950, at the Fredericia Furniture Fair, the two men met Karl Blindheim of the Norwegian factory Vik & Blindheim Møbelfabrikk in Sykkylven, who licensed both chairs for the Norwegian market. Vik & Blindheim marketed furniture without designer credits, and over the following decades the authorship of the Clam blurred; for years it circulated at auction under the wrong name.

Madsen died in 1989, before the renewed interest that would return his work to the light. The attribution was corrected only through patient research — family testimony from his daughter Johna Møhring-Andersen, from Flemming Schubell and from Ole Christian Hassing, alongside a 1989 recorded interview with Karl Blindheim. In 2022, nearly eighty years after it was conceived, an official new edition of the Clam Chair returned to production in agreement with Johna Møhring-Andersen: a solid beech frame with oak or walnut arms and legs, faithful to Arnold's form and Henry's cabinetmaking.

Respected in his own time but never given the recognition afforded his architect-trained peers, Madsen belongs to a parallel Danish tradition — the craftsmen who arrived at their forms through material rather than drawing. His life's work stands as a quiet argument for that way of making.$bio$
WHERE slug = 'arnold-madsen';