UPDATE designers
SET 
  biography = E'<strong>''Every piece must feel as if it has existed for centuries and yet could only have been made now.''</strong> — Achille Salvagni\n\nAchille Salvagni Atelier is the Rome-based design studio creating sculptural furniture, lighting and objects of extraordinary craftsmanship under the creative direction of architect and designer Achille Salvagni. Established as the production and edition arm of Salvagni''s practice, the Atelier translates his vision of classically inspired, contemporary collectible design into meticulously crafted limited editions and bespoke commissions.\n\nhttps://ifdm.design/wp-content/uploads/2022/10/Achille-Salvagni.jpg\n\nThe Atelier''s work is defined by an exceptional commitment to material and process. Each piece is produced by a network of master artisans across Italy: bronze is hand-cast and patinated in Tuscan foundries; Murano glass is mouth-blown by Venetian maestri; rare marbles — including Rosa Portogallo, Verde Alpi and Nero Marquina — are sourced from historic quarries and finished to exacting standards in Roman workshops.\n\nhttps://youtu.be/OaRgw7VoeY0?si=2TMVFBCk7obs8G-b | Achille Salvagni Portrait | poster:https://res.cloudinary.com/dif1oamtj/image/upload/w_1280,q_auto,f_auto/v1774856563/Screen_Shot_2026-03-30_at_3.41.52_PM_sezoxs.png\n\nThe Atelier''s collections draw on a remarkably wide range of historical references — ancient Roman architecture, Baroque dynamism, Art Deco geometry, mid-century Italian design — distilled through Salvagni''s architectural training into objects of striking originality. The Octopus chandelier, the Spider sconce and the Toro console are among its most recognised designs: sculptural, richly material and possessed of a theatrical presence that bridges the monumental and the intimate.\n\nhttps://www.achillesalvagni.com/wp-content/uploads/2024/05/London-Spring-2023-scaled.jpg\n\nAchille Salvagni Atelier maintains its own galleries in London, New York — at 817 Madison Avenue since 2022 — and Palm Beach, on Worth Avenue since 2026, alongside its Rome studio. It continues to be represented by Maison Gerard in New York. Its work has been exhibited at PAD London, Design Miami, TEFAF Maastricht and the Triennale di Milano, and is held in the permanent collection of the Philadelphia Museum of Art.\n\nhttps://www.achillesalvagni.com/wp-content/uploads/2024/05/Gio-cabinet-scaled.jpg\n\n<strong>The Atelier embodies Salvagni''s belief that collectible design, at its highest expression, is neither furniture nor sculpture but something rarer: an object that carries within it the memory of an entire civilisation, reimagined for the present.</strong>',
  biography_images = ARRAY[
    'https://ifdm.design/wp-content/uploads/2022/10/Achille-Salvagni.jpg',
    'https://www.achillesalvagni.com/wp-content/uploads/2024/05/London-Spring-2023-scaled.jpg',
    'https://www.achillesalvagni.com/wp-content/uploads/2024/05/Gio-cabinet-scaled.jpg'
  ],
  notable_works = (SELECT notable_works FROM designers WHERE slug = 'achille-salvagni-atelier'),
  philosophy = (SELECT philosophy FROM designers WHERE slug = 'achille-salvagni-atelier'),
  updated_at = now()
WHERE slug = 'achille-salvagni-designer';